apps/foods/urls.py
# -*- coding: utf-8 -*-
__author__ = 'lemon'

from django.conf.urls import url

from .views import FoodListView, FoodDetailView, AddFavView, AddCommentsView, AddShopCartView, ShopCartView
from .views import ConfirmOrder, CompletePayView, MyOrderView, MyOrderDetail, ShopCartDeleteView, CancelOrderView


urlpatterns = [
    # 菜单列表页
    url(r'^list/$', FoodListView.as_view(), name="food_list"),

    # 菜品详情页
    url(r'^detail/(?P<food_id>\d+)/$', FoodDetailView.as_view(), name="food_detail"),

    # 用户收藏
    url(r'add_fav/$', AddFavView.as_view(), name="add_fav"),

    # 添加课程评论
    url(r'^add_comment/$', AddCommentsView.as_view(), name="add_comment"),

    # 加入购物车
    url(r'^cart_add/(?P<food_id>\d+)/$', AddShopCartView.as_view(), name="cart_add"),

    # 购物车页面
    url(r'^shop_cart/$', ShopCartView.as_view(), name="shop_cart"),

    # 购物车删除
    url(r'^shop_delete/(?P<delete_id>\d+)/$', ShopCartDeleteView.as_view(), name="shop_delete"),

    # 确认订单
    url(r'^confirm_order/$', ConfirmOrder.as_view(), name="confirm_order"),

    # 完成支付
    url(r'^complete_pay/$', CompletePayView.as_view(), name="complete_pay"),

    # 我的订单
    url(r'^my_order/$', MyOrderView.as_view(), name="my_order"),

    # 订单详情
    url(r'^my_order_detail/(?P<order_id>\d+)/$', MyOrderDetail.as_view(), name="order_detail"),

    # 取消订单
    url(r'^cancel_order/(?P<order_id>\d+)/$', CancelOrderView.as_view(), name="cancel_order"),
]

apps/users/urls.py
# -*- coding: utf-8 -*-
__author__ = 'lemon'

from django.conf.urls import url

from .views import UserInfoView, ImageUploadView, UpdatePwdView, SendEmailCodeView, UpdateEmailView
from .views import MyFavFoodView, MyMessageView, UserFoodView

urlpatterns = [
    # 用户基本信息
    url(r'^info/$', UserInfoView.as_view(), name="user_info"),

    # 修改用户头像
    url(r'^image/upload/$', ImageUploadView.as_view(), name="image_upload"),

    # 个人中心修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name="update_pwd"),

    # 个人中心发送修改邮箱验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name="sendemail_code"),

    # 个人中心修改邮箱
    url(r'^update_email/$', UpdateEmailView.as_view(), name="update_email"),

    # 我的收藏
    url(r'^fav_food/$', MyFavFoodView.as_view(), name="fav_food"),

    # 我的消息
    url(r'^my_message/$', MyMessageView.as_view(), name="my_message"),

    # 点过的菜
    url(r'^user_food/$', UserFoodView.as_view(), name="user_food"),

]

weborder/urls.py
# -*- coding: utf-8 -*-
"""weborder URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.contrib import admin
import xadmin
from django.views.static import serve

from users.views import LoginView, IndexView, RegisterView, ActiveUserView, ForgetPwdView, ResetPwdView, ModifyPwdView
from users.views import LogoutView, TestPayView
from .settings import MEDIA_ROOT

urlpatterns = [
    # 网站后台
    url(r'^xadmin/', xadmin.site.urls),

    # 用户注册
    url(r'register/$', RegisterView.as_view(), name="register"),

    # 用户登录
    url(r'^login/$', LoginView.as_view(), name="login"),

    # 用户登出
    url(r'^logout/$', LogoutView.as_view(), name="logout"),

    # 首页
    url(r'^$', IndexView.as_view(), name="index"),

    # 验证码
    url(r'^captcha/', include('captcha.urls')),

    # 激活用户
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),

    # 忘记密码
    url(r'^forget/$', ForgetPwdView.as_view(), name="forget_pwd"),

    # 打开重置密码页面
    url(r'^reset/(?P<reset_code>.*)/$', ResetPwdView.as_view(), name="reset_pwd"),

    # 重置密码
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name="modify_pwd"),

    # 配置处理上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    # 富文本相关url
    url(r'^ueditor/',include('DjangoUeditor.urls')),

    # 菜单相关url配置
    url(r'^food/', include('foods.urls', namespace="food")),

    # 用户个人中心相关url配置
    url(r'^users/', include('users.urls', namespace="users")),

    url(r'^testpay/$', TestPayView.as_view(), name="testpay"),
]

apps/foods/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime

from django.db import models
from DjangoUeditor.models import UEditorField

from users.models import UserProfile


# Create your models here.


class Food(models.Model):
    name = models.CharField(verbose_name=u"菜名", max_length=50)
    price = models.IntegerField(verbose_name=u"价格", default=0)
    category = models.CharField(verbose_name=u"菜的类别", max_length=5,
                                choices=(("rh", u"热荤"), ("rs", u"热素"), ("lc", u"凉菜"),
                                         ("td", u"甜点"), ("zs", u"主食"), ("js", u"饮品")), default="rh")
    image = models.ImageField(verbose_name=u"图片", upload_to="food/%Y/%m", max_length=100, null=True, blank=True)
    taste = models.CharField(verbose_name=u"口味", max_length=20)
    detail = UEditorField(verbose_name=u"详细描述", width=600, height=300, imagePath="foods/ueditor/",
                          filePath="foods/ueditor/", null=True, blank=True)
    buy_nums = models.IntegerField(verbose_name=u"下单数", default=0)
    fav_nums = models.IntegerField(verbose_name=u"收藏数", default=0)
    add_time = models.DateTimeField(verbose_name=u"添加时间", default=datetime.now)

    class Meta:
        verbose_name = u"菜单"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(UserProfile, verbose_name=u"用户")
    has_pay = models.BooleanField(verbose_name=u"是否支付", default=False)
    total_money = models.IntegerField(verbose_name=u"总金额", default=0)
    order_time = models.DateTimeField(verbose_name=u"下单时间", default=datetime.now)
    preset_time = models.CharField(verbose_name=u"预订时间", max_length=20, default="")
    room_num = models.CharField(verbose_name=u"包间号", max_length=20, default="")
    order_status = models.CharField(verbose_name=u"订单状态", max_length=20,
                                    choices=(("weixiaofei", u"未消费"), ("yixiaofei", u"已消费"), ("yiquxiao", u"已取消")),
                                    default="weixiaofei")

    class Meta:
        verbose_name = u"订单"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return str(self.id)


class OrderDetail(models.Model):
    detail_id = models.IntegerField(primary_key=True, verbose_name=u"订单详情id", default=1)
    order = models.ForeignKey(Order, verbose_name=u"订单")
    food = models.ForeignKey(Food, verbose_name=u"菜单")
    quantity = models.IntegerField(verbose_name=u"数量", default=1)

    class Meta:
        verbose_name = u"订单详情"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return str(self.detail_id)


class Room(models.Model):
    name = models.CharField(verbose_name=u"包间名", max_length=20)
    category = models.CharField(verbose_name=u"种类", max_length=8,
                                choices=(("big", u"12人间"), ("middle", u"8人间"), ("small", u"6人间"), ("dating", u"大厅")))
    has_order = models.BooleanField(verbose_name=u"是否预订", default=False)
    add_time = models.DateTimeField(verbose_name=u"添加时间", default=datetime.now)

    class Meta:
        verbose_name = u"包间"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class ShopCart(models.Model):
    user = models.ForeignKey(UserProfile, verbose_name=u"用户")
    food = models.ForeignKey(Food, verbose_name=u"菜单")
    quantity = models.IntegerField(verbose_name=u"一种菜的数量", default=1)
    add_time = models.DateTimeField(verbose_name=u"添加时间", default=datetime.now)

    class Meta:
        verbose_name = u"购物车"
        verbose_name_plural = verbose_name

    def augment_price(self):
        return self.food.price * self.quantity

apps/users/forms.py
# -*- coding: utf-8 -*-
__author__ = 'lemon'

from django import forms
from captcha.fields import CaptchaField

from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=6)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=6)
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})


class ForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={"invalid": u"验证码错误"})


class ModifyForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=6)
    password2 = forms.CharField(required=True, min_length=6)


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'birthday', 'gender', 'address', 'mobile']


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']
        

templates/food-list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}菜单列表 - 在线点餐网{% endblock %}

{% block custom_bread %}
    <ol class="breadcrumb" style="background-color: white;">
        <li><a href="{% url 'index' %}">首页</a></li>
        <li class="active">菜单列表</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-9">

            <ul class="nav nav-pills nav-justified">
                <li class="{% if category == '' %}active{% endif %}"><a href="?ct=&sort={{ sort }}">全部</a></li>
                <li class="{% if category == 'rh' %}active{% endif %}"><a href="?ct=rh&sort={{ sort }}">热荤</a></li>
                <li class="{% if category == 'rs' %}active{% endif %}"><a href="?ct=rs&sort={{ sort }}">热素</a></li>
                <li class="{% if category == 'lc' %}active{% endif %}"><a href="?ct=lc&sort={{ sort }}">凉菜</a>
                </li>
                <li class="{% if category == 'td' %}active{% endif %}"><a href="?ct=td&sort={{ sort }}">甜点</a></li>
                <li class="{% if category == 'zs' %}active{% endif %}"><a href="?ct=zs&sort={{ sort }}">主食</a></li>
                <li class="{% if category == 'js' %}active{% endif %}"><a href="?ct=js&sort={{ sort }}">饮品</a>
                </li>
            </ul>
            <br/>
            <ul class="nav nav-tabs">
                <li class="{% if sort == '' %}active{% endif %}"><a href="?ct={{ category }}&sort=">最新 </a>
                </li>
                <li class="{% if sort == 'order' %}active{% endif %}"><a
                        href="?ct={{ category }}&sort=order">下单最多 ↓</a></li>
                <li class="{% if sort == 'fav' %}active{% endif %}"><a href="?ct={{ category }}&sort=fav">收藏最多
                    ↓</a>
                </li>
            </ul>
            <br/>
            <div class="row">
                {% for food in all_foods.object_list %}
                    <div class="col-md-4">
                        <div class="thumbnail">
                            <a target="_blank" href="{% url 'food:food_detail' food.id %}"><img src="{{ MEDIA_URL }}{{ food.image }}"
                                                                                alt="菜品图片"></a>
                            <div class="caption">
                                <p style="margin-left: 10px">
                                    <a target="_blank" style="text-decoration: none;" href="{% url 'food:food_detail' food.id %}">
                                        <i style="font-size: 20px">{{ food.name }}</i>
                                    </a>
                                </p>

                                <p style="margin-left: 10px; margin-right: 10px; margin-bottom: 35px">
                                    <span style="float: left"><i style="color: grey">已售{{ food.buy_nums }}份</i></span>
                                    <span style="float: right"><img src="{% static 'img/fav.png' %}"><i
                                            style="color: #ffa735">({{ food.fav_nums }})</i></span>
                                </p>

                                <p style="margin-bottom: 50px; margin-left: 10px; margin-right: 10px">
                                    <span style="float: left"><i style="font-size: 18px; color: red; font-weight: bold">￥{{ food.price }}</i></span>
                                    <span style="float: right" title=""><i style="color: orange;">{{ food.get_category_display }}</i></span>

                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="pageturn">
                <ul class="pagelist">

                    {% if all_foods.has_previous %}
                        <li class="long"><a
                                href="?{{ all_foods.previous_page_number.querystring }}">上一页</a></li>
                    {% endif %}

                    {% for page in all_foods.pages %}
                        {% if page %}
                            {% ifequal page all_foods.number %}
                                <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                            {% else %}
                                <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                            {% endifequal %}
                        {% else %}
                            <li><a href="" class="none">...</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if all_foods.has_next %}
                        <li class="long"><a
                                href="?{{ all_foods.next_page_number.querystring }}">下一页</a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </div>

        {#        <div class="col-md-3" style="margin-top: -15px">#}
        {#            <h3>热门菜品推荐</h3>#}
        {#        <div class="row">#}
        {#            {% for hot_food in hot_foods %}#}
        {#                <div class="col-md-12">#}
        {#                    <div class="thumbnail">#}
        {#                        <a href="{% url 'food:food_detail' hot_food.id %}">#}
        {#                            <img src="{{ MEDIA_URL }}{{ hot_food.image }}"/>#}
        {#                        </a>#}
        {#                        <div class="caption">#}
        {#                            <a style="text-decoration: none" href="{% url 'food:food_detail' hot_food.id %}">#}
        {#                                <h3>{{ hot_food.name }}</h3></a>#}
        {#                            <p>#}
        {#                                <span class="fl">价格：<i class="key">{{ hot_food.price }}<i style="font-size: 14px">元</i></i></span>#}
        {#                            </p>#}
        {#                            <br/>#}
        {##}
        {#                        </div>#}
        {#                    </div>#}
        {#                </div>#}
        {#            {% endfor %}#}
        {#        </div>#}
        {##}
        {#        </div>#}

        <div class="col-md-3">
            <div class="panel panel-default" style="border-color: white">
                <div class="panel-heading">
                    <h4>热门菜品推荐</h4>
                </div>
                <div class="panel-body">
                    <div class="row">
                        {% for hot_food in hot_foods %}
                            <div class="col-md-12">
                                <div class="thumbnail">
                                    <a href="{% url 'food:food_detail' hot_food.id %}">
                                        <img src="{{ MEDIA_URL }}{{ hot_food.image }}"/>
                                    </a>
                                    <div class="caption">
                                        <a style="text-decoration: none"
                                           href="{% url 'food:food_detail' hot_food.id %}">
                                            <h3>{{ hot_food.name }}</h3></a>
                                        <p>
                                            <span class="fl">价格：<i class="key">{{ hot_food.price }}<i
                                                    style="font-size: 14px">元</i></i></span>
                                        </p>
                                        <br/>

                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/forgetpwd.html
{% extends 'page-base.html' %}
{% load staticfiles %}

{% block title %}忘记密码 - 在线点餐网{% endblock %}

{% block content %}
    <div class="container">
    <div class="row" style="min-height: 600px; margin-top: 30px">
        <div class="col-md-8">
            <img src="{% static 'images/forgetimag.jpg' %}">
        </div>
        <div class="col-md-4">
            <h2>忘记密码</h2>
            <form id="jsFindPwdForm" method="post" action="{% url 'forget_pwd' %}" autocomplete="off">
                <div style="font-size: large; margin-top: 30px">
                    <input class="{% if forget_form.errors.email or msg %}myerrorput{% endif %} " type="text"
                           id="id_email" name="email" value="{{ forget_form.email.value|default_if_none:'' }}"
                           placeholder="请输入你的邮箱"/>
                </div>
                <div class="text-center" style="font-size: smaller; color: red">
                    {{ forget_form.errors.email }}{{ msg }}</div>

                <div class="mycaptcha {% if forget_form.errors.captcha %}myinputerrorput{% endif %}" style="font-size: large; margin-top: 40px;">
                    {{ forget_form.captcha }}
                </div>
            <div class="text-center" style="font-size: smaller; color: red">
                    {{ forget_form.errors.captcha }}</div>

                <input type="hidden" name="sms_type" value="1">
                <input class="btn btn-success myForget" style="margin-top: 40px;" id="jsFindPwdBtn" type="submit" value="提交"/>
                {% csrf_token %}
            </form>
                    <div class="text-left" style="margin-top: 20px">你还可以 <a href="{% url 'login' %}">[直接登录]</a></div>

        </div>
    </div>
</div>

{% endblock %}

{% block custom_js %}
<script src="{% static 'js/validateDialog.js' %}" type="text/javascript"></script>
{#    <script type="text/javascript">#}
{#    $('.myForget').on('click', function () {#}
{#       alert("忘记密码链接已成功发送至您的邮箱，请登录邮箱点击链接修改密码。");#}
{#    });#}
{#    </script>#}
{% endblock %}

templates/page-base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}登录-在线点餐{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/mycss.css' %}">
    <style>
        input {
            border: 0;
            border-bottom: 1px solid #E3E3E3;
            width: 300px;
            height: 30px;
            margin: 10px;
        }
    </style>
{% block custom_css %}{% endblock %}
</head>
<body>
<!-- 导航栏 -->
<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" data-target="#navbar" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">在线点餐网</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">

            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home"></span> 首页</a></li>
                <li><a href={% url 'login' %}><span class="glyphicon glyphicon-log-in"></span> 登录</a></li>
                <li><a href={% url 'register' %}><span class="glyphicon glyphicon-user"></span> 注册</a></li>
                <li><a href="http://127.0.0.1:8000/xadmin/"><span class="glyphicon glyphicon-share-alt">后台</span></a></li>
            </ul>

        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<div class="myfooter">
    <div class="container-fluid">
        <div class="container">
            <br/>
            <div class="row">
                <div class="col-md-4">
                    <h2>联系我们</h2>
                    <br/>
                    <h4>Tel: 6233-1111
                        <small>（周一至周日 8:00-22:00）</small>
                    </h4>
                    <h4>Email: lemonyolo@sina.com</h4>
                </div>

                <div class="col-md-4">
                    <h2>本站链接</h2>
                    <br/>
                    <h5><a href="{% url 'index' %}">首页</a></h5>
                    <h5><a href="{% url 'food:food_list' %}">全部菜单</a></h5>
                    <h5><a href="{% url 'food:shop_cart' %}">购物车</a></h5>
                    <h5><a href="{% url 'food:my_order' %}">我的订单</a></h5>
                    <h5><a href="{% url 'users:user_info' %}">个人中心</a></h5>
                </div>

                <div class="col-md-4">
                    <br/>
                    <img src="{% static 'images/erweima.jpg' %}" width="180px" height="180px">
                </div>
            </div>
            <br/>
            <div class="text-center">
                <h6>The Website Is Powered By <a href="http://lemonline.top">Lemon</a>, Design By <a href="http://lemonline.top">Lemon</a></h6>
                <h6>Copyright © 2017 Lemon All Rights Reserved.</h6>
            </div>
        </div>


    </div>
</div>
<script src="{% static 'jquery/jquery-3.1.1.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/login.js' %}" type="text/javascript"></script>

{% block custom_js %}{% endblock %}
</body>
</html>

templates/shopping-cart.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}购物车 - 在线点餐网{% endblock %}

{% block custom_bread %}
    <ol class="breadcrumb" style="background-color: white;">
        <li><a href="{% url 'index' %}">首页</a></li>
        <li class="active">购物车</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                {% for shop_cart in shop_carts %}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-3">
                                <a href="{% url 'food:food_detail' shop_cart.food.id %}">
                                    <img width="200" height="120" src="{{ MEDIA_URL }}{{ shop_cart.food.image }}"/>
                                </a>
                            </div>
                            <div class="col-md-7">
                                <a href="{% url 'food:food_detail' shop_cart.food.id %}">
                                    <span style="font-size: 25px">{{ shop_cart.food.name }}</span>
                                </a>
                                <p>
                                    类别：<span>{{ shop_cart.food.get_category_display }}</span>
                                </p>
                                <p>
                                    数量：<span>{{ shop_cart.quantity }}</span>
                                </p>
                                <p>
                                    小计：<span style="color: red">¥{{ shop_cart.augment_price }}</span>
                                </p>
                            </div>
                            <div class="col-md-2">
                                <a href="{% url 'food:shop_delete' shop_cart.food.id %}" class="btn btn-danger btn-lg" id="cartDelete">删除</a>
                            </div>
                        </div>
                    </div>
                    <br/>
                {% endfor %}
            </div>

            <form action="{% url 'food:confirm_order' %}" method="post" autocomplete="off">
                <div class="col-md-9">
                    预订时间：
                    <input type="text" id="preset_time" name="preset_time" value="" readonly="readonly"/>

                    预定包间：
                    <select name="room_num">
                        {% for room in rooms %}
                            <option value="{{ room.name }}">{{ room.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            <div class="col-md-3 text-right">
                 <div>
                     <strong>应付金额：</strong><span style="font-size: 30px; color: red">¥{{ total_price }}</span>
                    <input type="hidden" name="total_price" value="{{ total_price }}">
                </div>
                <br/><br/>
                <input type="submit" class="btn btn-success btn-lg" value="确认支付">
            </div>

                {% csrf_token %}
            </form>
        </div>


    </div>
<br/><br/><br/>
    <script type="text/javascript">
        $(function () {
            laydate({
                elem: '#preset_time',
                format: 'YYYY-MM-DD hh:mm',
                min: laydate.now(+1),
                max: laydate.now(+7),
                istime: true,
                festival: true

            });
        });
    </script>
    <script type="text/javascript">
    $('#cartDelete').on('click', function () {
        alert("删除成功！");
    });
    </script>
{% endblock %}

templates/shopping-order-detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}订单详情 - 在线点餐网{% endblock %}

{% block custom_bread %}
    <ol class="breadcrumb" style="background-color: white;">
        <li><a href="{% url 'index' %}">首页</a></li>
        <li><a href="{% url 'food:my_order' %}">我的订单</a></li>
        <li class="active">订单详情</li>
    </ol>
{% endblock %}

{% block content %}
    <div style="min-height: 300px">
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>订单号</th>
            <th>菜名</th>
            <th>单价</th>
            <th>数量</th>
        </tr>
        </thead>
        <tbody>
        {% for order_detail in order_details %}
        <tr>
        <td>1000{{ order_detail.order_id }}</td>
        <td><img style="height: 60px; width: 60px" src="{{ MEDIA_URL }}{{ order_detail.food.image }}"><a href="{% url 'food:food_detail' order_detail.food_id %}">&nbsp;&nbsp;{{ order_detail.food.name }}</a></td>
        <td style="color: red">¥{{ order_detail.food.price }}</td>
        <td>{{ order_detail.quantity }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <p class="text-right">
    {% if order_status == "weixiaofei" %}
        <button class="btn btn-danger" data-toggle="modal" data-target="#myModal">取消订单</button>
        {% else %}
        <a class="btn btn-danger disabled" href="#">订单已失效</a>
        {% endif %}
    </p>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                &times;
                            </button>
                            <h4 class="modal-title" id="myModalLabel">
                                警告：
                            </h4>
                        </div>
                        <div class="modal-body">
                            距离预定时间＜12小时取消订单，商家将不会退还预付金。
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                            </button>
                            <a class="btn btn-danger" href="{% url 'food:cancel_order' my_order_id %}">
                                确认取消
                            </a>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal -->
            </div>
    </div>

{% endblock %}